### ISSUE TITLE
Some users not able to save more than one user role.

### ISSUE THREAD

**Issue by ledow** [JunglePlugins/User-Menus#10]
I just installed the version from the WP store and it seems to work, except that if I want a menu visible to, say, Administrator and Editor roles, then it only ever saves Editor (without any warning that it's doing anything differently).  The menu also ends up reflecting that (i.e. only shows for one of the two).

A couple of people also reported the same problem on the WP store comments.

**Comment by danieliser** [comment]
@ledow - Unfortunately I wasn't able to duplicate the issue described here or on the forums with a clean install.

https://www.loom.com/share/526d04b86a944bab921121498e2a66d4

This likely means its a conflict with another plugin that we simply aren't aware of thus far.

If you can use the Health Check plugin's troubleshooting mode to figure out which plugin/theme your having a conflict with that would be helpful.

But as it stands our code in these cases is very straightforward:

1. We save all roles as long as they are valid, but the list of valid roles is also what we use to generate the list of role checkboxes, so if its there and checked we save it: https://github.com/JunglePlugins/User-Menus/blob/master/includes/classes/admin/menu-settings.php#L166-L171
2. When actually checking whether a menu item should be rendered and checking if they have the required role, we simply loop over all checked roles and return true if the `current_user_can( $role )` which checks if they have that permission. It returns false by default, and as soon as one is true we quit checking the rest. Very efficient and hard to say there is something that could be changed there. https://github.com/JunglePlugins/User-Menus/blob/master/includes/classes/site/menus.php#L54-L66

First guess is that something on your site is likely filtering roles inappropriately. But hard to say.

Let me know. Happy to dig in further.

**Comment by danieliser** [comment]
@ledow, @agonzal26 - Any luck figuring out where the conflict comes from?
