### ISSUE TITLE
Subject to delete

### ISSUE THREAD

**Issue by agonzal26** [JunglePlugins/User-Menus#11]
Hi :)
Plugin works perfectly on my computer !
But when going to my website with a mobile, links are here :(

![thumbnail_Screenshot_20190927-112926_Firefox](https://user-images.githubusercontent.com/55876496/65759434-34efad00-e11b-11e9-93ae-b1637809908d.jpg)

If you want to test it : https://www.neoalternative.com/
You're not going to see this 3 icons on computer.

I have no idea how to solve this. Can you help me with this one please?

Thanks for your support ;)

**Comment by fpcorso** [comment]
Hey @agonzal26 

Thanks for reporting this issue! I have not seen this before. I went to your site on my own phone but did not see those links. Can you say which OS and which browser you are using on your phone?

**Comment by danieliser** [comment]
![image](https://user-images.githubusercontent.com/847818/65822142-21bd0a00-e20d-11e9-9eee-1393a170f4c6.png)

I'm not seeing it on mobile. Is it possible @agonzal26 that your site uses caching that wasn't manually cleared and just took a while to expire normally?

**Comment by danieliser** [comment]
Otherwise the only possible issue for one menu working correctly and another not is that the second menu is being rendered without using the normal methods. IE a custom menu walker & rendering function which is totally plausible in some themes if they wanted a custom output for the mobile menu.

**Comment by danieliser** [comment]
@agonzal26 - I'm assuming by your title change you got it already?

**Comment by agonzal26** [comment]
Yes sorry...
Wrong issue finally. So the real issue is related with the last topic which is multiple role can't be selected. When I select roles only a random one will be selected after saving the menu.
And after as I have a cache for computer and one for mobile, maybe phone cache cleaning wasn't done yet. I can't remember exactly in which order things happened sorry...
But things is it was coming from role selection which was fixed on one role only.
Then I've just put for logged in users without selecting any role and it looks like it's working. I didn't tested all role yet but for the moment it's ok :)

As it was my mistake for not checking correctly that the save of roles was good and so it was a different issue I just wanted to close this ticket which was irrelevant.

But thanks a lot for your quick answers and support.

If I find issues with some role then I will check with which plugin there is a conflict and tell you ;)

**Comment by danieliser** [comment]
@agonzal26 Can you test with the Health Check plugin's Troubleshooting mode? Its gotta be a conflict causing that not to save correctly, see #10 as our code does work as expected on clean install. Gotta be a conflict.
