### ISSUE TITLE
Change review class to check manage_options or edit_others_posts

### ISSUE THREAD

**Issue by danieliser** [JunglePlugins/User-Menus#2]

**Comment by danieliser** [comment]
Changing to edit_theme_options instead. That is the same capabaility required to use the nav menu editor in the first place.

**Comment by danieliser** [comment]
@fpcorso - Any thoughts, I guess this change could have an impact on number of reviews solicited. IE currently edit_posts cap is had by all editors and various other roles. Now only users with ability to edit menus will see it. So basically admins, not editors.

Also since the dismissal is stored on a per user basis, a site with 1 admin & 2 editors can solicit 3 reviews (wishful thinking).

**Comment by fpcorso** [comment]
@danieliser I know there are many WP sites that use the editor role for actual content editors who have no say or knowledge of the behind the scenes working of the site. 

So, for them, they find the notifications annoying.

I tested this with WP Health and did see a small decrease in reviews the plugin was receiving but it wasn't enough for me to decide to reverse it. That said, User Menus has 12,000 more installs so it may be more noticeable.
