### ISSUE TITLE
Insecure version of the Freemius Framework reported by WPScan

### ISSUE THREAD

**Issue by angelsguitar** [JunglePlugins/User-Menus#41]
According to WPScan, the plugin is using...
> an insecure version of the Freemius Framework, which is lacking CSRF and/or authorisation in some of its AJAX actions. As a result, any authenticated users, such as subscriber could access the debug logs. Unauthenticated attackers could also make a logged in admin toggle the debug mode via a CSRF attack.

The full report can be found [here](https://wpscan.com/vulnerability/6dae6dca-7474-4008-9fe5-4c62b9f12d0a). Also reported by iThemes Security [here](https://ithemes.com/blog/wordpress-vulnerability-report-march-2-2022/#400-plugins-themes-impacted-by-insecure-freemius-version).

**Comment by danieliser** [comment]
@angelsguitar Already patched and released last night, thanks for the report.
